name: JoyOscope
favicon: null
layout_spectrum: 0.8666646871715784
typography_spectrum: 0.4882669385988265
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.3261069862637669
  lightness: 0.8807003777474165
  saturation: 0.9672213289886713
  rhythmicContrast: 0.05309469439089298
purpose: []
